name: "RenPy Web Build"
author: 'PaxlavaGames'
description: "GitHub action to build RenPy projects for WEB"
inputs:
  path:
    description: "RenPy project path"
    required: false
    default: "."
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
branding:
  color: 'yellow'
  icon: 'box'
