name: Build RenPy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install RenPy
      uses: PaxlavaGames/renpy-install@v0.2.0
      with:
        version: "8.2.0"
    - name: Build RenPy
      uses: PaxlavaGames/renpy-web-build@main
      with:
        path: "./testing"
    - name: Check results
      run: |
        ls
        ls ./FunAdventureinTurkey-1.0-dists
